[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
recyclerviewKtx = "1.4.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
retrofitVersion = "3.0.0"
coroutineRef = "1.10.2"
okhttpVersion = "5.3.0"
converterMoshi = "3.0.0"
kotlinXSerialization = "1.9.0"
kspRef = "2.3.0"
moshiRef = "1.15.2"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
fragmentTesting = "1.8.9"
coilRef = "2.7.0"
moshiKotlinRef = "1.15.2"
pagingRef = "3.3.6"
datastoreRef = "1.1.7"
workManagerRef = "2.11.0"
safeargs = "2.9.6"
browserRef = "1.3.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-recycler-view = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerviewKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion"}
squareup-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttpVersion"}
squareup-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "converterMoshi"}
squareup-moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlinRef"}
squareup-moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshiRef"}
squareup-moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshiRef"}
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutineRef"}
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutineRef"}
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinXSerialization" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragmentTesting" }
coil = { group = "io.coil-kt", name = "coil" , version.ref = "coilRef"}
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "pagingRef"}
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "pagingRef"}
squareup-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpVersion" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreRef" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManagerRef" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browserRef"}


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kspRef"}
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "safeargs" }